// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtnTCq_c1CUtbN7hUshXd8xUTvkCBiElE',
    appId: '1:962528026415:web:b60b7df2386b7a82ae4bda',
    messagingSenderId: '962528026415',
    projectId: 'mcc-1-3a29e',
    authDomain: 'mcc-1-3a29e.firebaseapp.com',
    databaseURL: 'https://mcc-1-3a29e-default-rtdb.firebaseio.com',
    storageBucket: 'mcc-1-3a29e.appspot.com',
    measurementId: 'G-E6K9NYRPW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3znG0tXNc0okyYzT1CZb7MAudJLUfh4',
    appId: '1:962528026415:android:e26e45ae6e4fa2b2ae4bda',
    messagingSenderId: '962528026415',
    projectId: 'mcc-1-3a29e',
    databaseURL: 'https://mcc-1-3a29e-default-rtdb.firebaseio.com',
    storageBucket: 'mcc-1-3a29e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzJOF54J_tVAUko051lF65H2dwFzfPmU8',
    appId: '1:962528026415:ios:c1c7fb523b1d0258ae4bda',
    messagingSenderId: '962528026415',
    projectId: 'mcc-1-3a29e',
    databaseURL: 'https://mcc-1-3a29e-default-rtdb.firebaseio.com',
    storageBucket: 'mcc-1-3a29e.appspot.com',
    iosClientId: '962528026415-m3qp9rh0s3q1c0orahmk8d0b0e268o74.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcc2realtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzJOF54J_tVAUko051lF65H2dwFzfPmU8',
    appId: '1:962528026415:ios:c1c7fb523b1d0258ae4bda',
    messagingSenderId: '962528026415',
    projectId: 'mcc-1-3a29e',
    databaseURL: 'https://mcc-1-3a29e-default-rtdb.firebaseio.com',
    storageBucket: 'mcc-1-3a29e.appspot.com',
    iosClientId: '962528026415-m3qp9rh0s3q1c0orahmk8d0b0e268o74.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcc2realtime',
  );
}
